uniLogo: PLOVER
uniName: Plover University
uniRights: All rights reserved
uniPortalName: UMS Online
uniPortalSubName: University Online Services
uniTitle: Welcome to UMS Online
uniSubTitle: Select your portal below to access ums online services.


uniStudentPortalTitle: Student Portal
uniStudentPortalText: Access student services, academic information, courses and university resources.
uniStudentPortalButtonName: Student Login

uniTeacherPortalTitle: Teacher Portal
uniTeacherPortalText: Access teaching services, courses, attendance and academic activities.
uniTeacherPortalButtonName: Teacher Login

uniAdminPortalTitle: Admin Portal
uniAdminPortalText: Access administrative, management modules and system functionalities.
uniAdminPortalButtonName: Admin Login

onlineurl:online.ucp.edu.pk
uniname:Plover University


unitel:Tel: +92-42-5755314-7, Fax +92-42-5857846
unihomeadd:www.plover.edu
uniemail:info@plover.edu 

DbUrl:jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.ap-singapore-1.oraclecloud.com))(connect_data=(service_name=g4cbc0ce0f22fd9_ums_tp.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
Developer:YourStrong@Password11
id:ucp